name: deploy

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.licenses=MIT OR Apache-2.0

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: cowprotocol/autodeploy@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          pods: dfusion-v2-hdnode-mainnet,dfusion-v2-hdnode-rinkeby,dfusion-v2-hdnode-xdai
          url: ${{ secret.AUTODEPLOY_URL }}
          token: ${{ secrets.AUTODEPLOY_TOKEN }}
